language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - mysql -e 'create database symfony_test'
  - composer self-update
  - composer install --no-interaction
  - php bin/console doc:mig:mig --env=test

script:
  - vendor/bin/phpmd src/ text phpmd.xml
  - vendor/bin/phpcs --extensions=php --warning-severity=0 --report=full --standard=phpcs.xml src
  - vendor/bin/phpcpd --exclude src/AppBundle/Entity src
  - vendor/bin/phpunit --colors=auto
  - vendor/bin/behat --colors --format=pretty
